server:
  port: 8080
spring:
  application:
    name: auth-service
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 763522976792-s9uqqoals8b1vcavkqfmq23otobpd7ih.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            user-name-attribute: email
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

jwt:
  secret: SOME256BIT_SECRET_KEY_SHOULD_BE_32+CHARS_ECOMMERCE_256_CHARS_DEMO_INVERT
  expiration: 3600000  # 1 hour in ms

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path:  /auth/api/actuator