spring:
  security:
    oauth2:
      client:
        registration:
          google:
#            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
#            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            client-id: 763522976792-efvnennkch02ti2an55n1beranvq239e.apps.googleusercontent.com
            client-secret: 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
            # Initial minimal scopes
            scope: openid, profile, email
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
        provider:
          google:
            issuer-uri: https://accounts.google.com
server:
  servlet:
    session:
      cookie:
        name: APPSESSION
        http-only: true
        secure: true
        same-site: Lax
        path: /
app:
  security:
    internal-jwt:
      issuer: https://bff.example.com
      ttl-seconds: 900
      hmac-secret: "CHANGE_ME_MIN_32_CHARS_LONG_SAMPLE_SECRET_KEY_1234567890"
  gmail:
    enabled: true
    # Additional Gmail scopes requested incrementally, not at initial login:
    incremental-scopes:
      - https://www.googleapis.com/auth/gmail.readonly
  downstream:
    product:
      base-url: "http://localhost:8081/"

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /auth/api/actuator